Repository librecorps/resources, pull requests merged in 2020-03, with the labels that each got.

#7 Typo correction DeHaan <-- DeHann
  content/community/reading-list.md
Labels: enhancement

#9 ci: Use Travis CI to build and deploy Hugo docs (closes #8)
  .travis.yml
  config.toml
Labels: new change, quality assurance

#11 ci: Rework Hugo extraction logic
  .travis.yml
Labels: blocked, bug, quality assurance

#12 gitignore: Cover more tools and editors
  .gitignore
Labels: contributor experience, new change

#13 Remove automatically-generated cruft from Hugo
  resources/_gen/assets/css/css/style.css_d3f53f09220d597dac26fe7840c31fc9.content
  resources/_gen/assets/css/css/style.css_d3f53f09220d597dac26fe7840c31fc9.json
  resources/_gen/assets/js/js/script.js_d3f53f09220d597dac26fe7840c31fc9.content
  resources/_gen/assets/js/js/script.js_d3f53f09220d597dac26fe7840c31fc9.json
Labels: contributor experience, improvement

#14 Housekeeping: Miscellaneous polish
  .gitmodules
  config.toml
  content/ai/milestone-roadmap.md
  content/ai/traps.md
  content/contact/_index.en.md
  content/elements/_index.en.md
  data/en/faq.yml
  themes/dot-hugo-documentation-theme/layouts/contact/list.html
Labels: contributor experience, improvement

#15 Upgrade site content to Dot theme 2.0
  config.toml
  content/ai/_index.en.md
  content/community/_index.en.md
  content/legal/_index.en.md
  content/outreach/_index.en.md
  content/product-management/_index.en.md
  content/tooling/_index.en.md
  i18n/en.yaml
Labels: bug

#16 Enable git timestamps and emoji
  config.toml
Labels: improvement

#17 Add "Open Hardware" section
  config.toml
  content/hardware/_index.en.md
Labels: new change

#19 ai: Improve formatting on Model Card page
  content/ai/model-card.md
Labels: improvement

#20 README/LICENSE: Reorganize root dir and content dir
  LICENSE.txt
  README.md
  content/LICENSE.txt
  content/README.md
Labels: documentation, improvement

#21 Reading lists: Break up into smaller docs
  content/community/reading-list.md
  content/hardware/reading-list.md
  content/legal/reading-list.md
  content/outreach/reading-list.md
  content/product-management/reading-list.md
  content/tooling/reading-list.md
Labels: improvement

#22 Rename product-management to project-management
  .github/CONTRIBUTING.md
  README.md
  config.toml
  content/product-management/_index.en.md
  content/project-management/_index.en.md
  content/project-management/preliminary-interview-template.en.md
  content/project-management/reading-list.md
Labels: improvement

#23 WIP: Add Open Hardware research draft
  content/hardware/research.md
Labels: new change

#24 hardware: Add case studies and licensing from Pen
  content/hardware/research.md
Labels: improvement, research

#25 ci: Update Hugo to v0.68.3
  .travis.yml
Labels: bug, quality assurance

#26 hardware: Add notes on emerging COVID-19 case and patents
  content/hardware/research.md
Labels: improvement, research

#27 legal: Add "What is copyleft?" by @funnelfiasco
  content/legal/reading-list.md
Labels: improvement

#28 legal: Add AGPL primer, comparison of GPL/AGPL/LGPL to readings
  content/legal/reading-list.md
Labels: improvement
